global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'custom-connector'
    static_configs:
      - targets: ['kafka-connect:8090']
  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['kafka-connect:9876']


